#!/usr/bin/sh

_files="$@"

# If there are no files, there's nothing for us to do
[ -z $_files ] && exit 0

for f in $_files; do
    # Only process files that match the following extensions
    if [ "${f##*.}" = "tf" ] || [ "${f##*.}" = "tfvars" ]; then
        terraform fmt "${f}"
        git add "${f}"
    fi
done

exit 0
